# Generated by Django 4.1.1 on 2024-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_pointtokentransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='About me'),
        ),
    ]
